"""Pipeline 预设 DeveloperSpec 模板——基于 NYC 交通数据仓库真实数据。

数据源：D:\\ProgramData\\Datawarehouse\\纽约市城市交通\\nyc_transport.duckdb
表结构、行数、枚举值均来自实际数据库查询（2026-07-06）。

提供 6 个 DeveloperSpec 模板供前端 SPA 使用：

- aggregation: 出租车日报表——按日期/行政区汇总行程量与收入
- label: 行程距离分类标签——CASE WHEN 距离分级（短途/中途/长途/异常）
- multi_step: 多步骤行程分析——三表 Join（行程事实 + 出租区域维 + 日期维）+ 聚合
- join: 行程明细宽表——两表 Join 展开区域名称
- window: 行政区 Top10 出租区域——ROW_NUMBER 分组排序
- empty: 自定义空模板——从零开始编写
"""

# ruff: noqa: E501 — 模板内容为长 markdown 字符串，换行破坏可读性

TEMPLATES: list[dict] = [
    {
        "template_id": "tpl_aggregation",
        "name": "出租车日报表",
        "description": "单表聚合——按日期/行政区统计行程量和收入，如日报、周报",
        "category": "aggregation",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.taxi_daily_report\n"
            "  target_grain: [pickup_date_key, borough]\n"
            '  summary: "按日期和行政区统计出租车行程量和收入"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips\n"
            "      alias: ft\n"
            "      row_count: ~8032万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "        - name: dropoff_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "        - name: passenger_count\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: distance_miles\n"
            "          type: double\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: total_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: trip_source\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [yellow, green, fhv, fhvhv]\n"
            "        - name: is_distance_outlier\n"
            "          type: boolean\n"
            "          nullable: true\n"
            "\n"
            "    - name: silver.taxi_zone\n"
            "      alias: tz\n"
            "      row_count: ~265\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: location_id\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 维度表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: borough\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [Manhattan, Brooklyn, Queens, Bronx, Staten Island, EWR, Unknown]\n"
            "        - name: zone_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: service_zone\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: trip_count\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: trip_id\n"
            "      alias: trip_count\n"
            "    - metric_name: total_fare\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: fare_amount\n"
            "      alias: total_fare\n"
            "    - metric_name: avg_distance\n"
            "      aggregation: AVG  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: distance_miles\n"
            "      alias: avg_distance\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: pickup_date_key\n"
            "      column_ref: pickup_date_key\n"
            "    - dimension_name: borough\n"
            "      column_ref: borough\n"
            "\n"
            "  joins:\n"
            "    - left_table: ft\n"
            "      right_table: tz\n"
            "      left_key: pickup_location_id\n"
            "      right_key: location_id\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: pickup_date_key\n"
            "      type: integer\n"
            "    - name: borough\n"
            "      type: varchar\n"
            "    - name: trip_count\n"
            "      type: bigint\n"
            "    - name: total_fare\n"
            "      type: decimal(12,2)\n"
            "    - name: avg_distance\n"
            "      type: double\n"
            "---\n"
            "\n"
            "# 出租车日报表\n"
            "\n"
            "## 业务目标\n"
            "按日期和行政区统计行程量、总收入和平均距离。\n"
            "数据范围：2026年Q1 NYC 出租车 + FHV 行程数据（Yellow/Green/FHV/FHVHV 四种来源）。\n"
            "\n"
            "## 加工步骤\n"
            "1. 从 gold.fact_trips 扫描行程记录（含 pickup_at 时间过滤，避免全表扫描）\n"
            "2. 过滤掉距离异常记录 is_distance_outlier = false\n"
            "3. 关联 silver.taxi_zone 获取上客点 borough\n"
            "4. 按 trip_date（从 pickup_at 截取）+ borough 汇总行程量、总收入和平均距离\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_label_table",
        "name": "行程距离分类标签",
        "description": "CASE WHEN 分类打标——按行程距离分级（短途/中途/长途/异常）",
        "category": "label",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: label_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.trip_distance_label\n"
            "  target_grain: [trip_id]\n"
            '  summary: "行程距离分类打标——短途/中途/长途/异常"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips\n"
            "      alias: ft\n"
            "      row_count: ~8032万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: distance_miles\n"
            "          type: double\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: total_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: passenger_count\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: is_distance_outlier\n"
            "          type: boolean\n"
            "          nullable: true\n"
            "        - name: is_time_anomaly\n"
            "          type: boolean\n"
            "          nullable: true\n"
            "\n"
            "  output_columns:\n"
            "    - name: trip_id\n"
            "      type: varchar\n"
            "    - name: pickup_at\n"
            "      type: timestamp\n"
            "    - name: distance_miles\n"
            "      type: double\n"
            "    - name: fare_amount\n"
            "      type: decimal(12,2)\n"
            "    - name: total_amount\n"
            "      type: decimal(12,2)\n"
            "    - name: passenger_count\n"
            "      type: bigint\n"
            "    - name: distance_category\n"
            "      type: varchar\n"
            "---\n"
            "\n"
            "# 行程距离分类标签\n"
            "\n"
            "## 业务目标\n"
            "对行程数据按距离分级打标：短途（≤2英里）、中途（2-10英里）、长途（>10英里）、\n"
            "异常（距离为空或标记为异常值）。用于分析不同距离段的出行模式和定价。\n"
            "\n"
            "## 分类逻辑（CASE WHEN）\n"
            "- distance_miles IS NULL OR is_distance_outlier = true → unknown（未知/异常）\n"
            "- distance_miles <= 2 → short（短途）\n"
            "- distance_miles > 2 AND distance_miles <= 10 → medium（中途）\n"
            "- distance_miles > 10 → long（长途）\n"
            "\n"
            "## 数据说明\n"
            "- 数据源：gold.fact_trips（8032万行，2026Q1 含历史数据）\n"
            "- 距离分布：min=0, avg=4.94, max=328522.20 英里\n"
            "- 建议添加 pickup_at 时间过滤缩小处理范围\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_multi_step",
        "name": "多步骤行程分析",
        "description": "多表 Join + 聚合——事实表关联出租区域维和日期维，按日期/行政区/区域统计",
        "category": "multi_step",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.zone_trip_analysis\n"
            "  target_grain: [pickup_date_key, borough, zone_name]\n"
            '  summary: "多步骤行程分析——关联出租区域维和日期维，按日期/行政区/区域统计行程量"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips\n"
            "      alias: ft\n"
            "      row_count: ~8032万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "        - name: passenger_count\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: distance_miles\n"
            "          type: double\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: total_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: trip_source\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [yellow, green, fhv, fhvhv]\n"
            "        - name: is_distance_outlier\n"
            "          type: boolean\n"
            "          nullable: true\n"
            "\n"
            "    - name: silver.taxi_zone\n"
            "      alias: tz\n"
            "      row_count: ~265\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: location_id\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 维度表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: borough\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [Manhattan, Brooklyn, Queens, Bronx, Staten Island, EWR, Unknown]\n"
            "        - name: zone_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: service_zone\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "    - name: gold.dim_date\n"
            "      alias: dd\n"
            "      row_count: ~1.1万\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: date_key\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 日期维表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: date\n"
            "          type: timestamp\n"
            "          nullable: true\n"
            "        - name: year\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: quarter\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: month\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: day_of_week_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: is_weekend\n"
            "          type: boolean\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: trip_count\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: trip_id\n"
            "      alias: trip_count\n"
            "    - metric_name: total_fare\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: total_amount\n"
            "      alias: total_fare\n"
            "    - metric_name: avg_distance\n"
            "      aggregation: AVG  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: distance_miles\n"
            "      alias: avg_distance\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: pickup_date_key\n"
            "      column_ref: pickup_date_key\n"
            "    - dimension_name: borough\n"
            "      column_ref: borough\n"
            "    - dimension_name: zone_name\n"
            "      column_ref: zone_name\n"
            "\n"
            "  joins:\n"
            "    - left_table: ft\n"
            "      right_table: tz\n"
            "      left_key: pickup_location_id\n"
            "      right_key: location_id\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "    - left_table: ft\n"
            "      right_table: dd\n"
            "      left_key: pickup_date_key\n"
            "      right_key: date_key\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: pickup_date_key\n"
            "      type: integer\n"
            "    - name: borough\n"
            "      type: varchar\n"
            "    - name: zone_name\n"
            "      type: varchar\n"
            "    - name: trip_count\n"
            "      type: bigint\n"
            "    - name: total_fare\n"
            "      type: decimal(12,2)\n"
            "    - name: avg_distance\n"
            "      type: double\n"
            "---\n"
            "\n"
            "# 多步骤行程分析\n"
            "\n"
            "## 业务目标\n"
            "三表关联：行程事实表 + 出租区域维 + 日期维，按日期/行政区/区域名称统计\n"
            "行程量、总收入和平均距离。\n"
            "\n"
            "## 加工步骤\n"
            "1. 从 gold.fact_trips 扫描行程记录，添加 pickup_at 时间过滤（如 pickup_at >= '2026-01-01'）\n"
            "2. 过滤异常数据：is_distance_outlier = false\n"
            "3. LEFT JOIN silver.taxi_zone ON ft.pickup_location_id = tz.location_id（获取 borough + zone_name）\n"
            "4. LEFT JOIN gold.dim_date ON ft.pickup_date_key = dd.date_key（获取日期属性）\n"
            "5. 按 pickup_date_key + borough + zone_name 汇总，聚合 trip_count / total_fare / avg_distance\n"
            "\n"
            "## 关联推理提示\n"
            "- ft.pickup_location_id → tz.location_id（事实表上客区域编码 → 维表区域编码）\n"
            "- ft.pickup_date_key → dd.date_key（事实表日期键 → 日期维整数键）\n"
            "- 出租区域维表仅 265 行，可全量加载后内存 Join\n"
            "- **务必添加 pickup_at 时间过滤条件**，8032 万行全表扫描不可接受\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_two_table_join",
        "name": "行程明细宽表",
        "description": "两表 Join——事实表关联出租区域维，展开上客/下客区域名称，不做聚合",
        "category": "join",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: detail_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.trip_detail_wide\n"
            "  target_grain: [trip_id]\n"
            '  summary: "行程明细宽表——关联出租区域维表，展开上客/下客区域名称和行政区"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips\n"
            "      alias: ft\n"
            "      row_count: ~8032万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "        - name: dropoff_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: dropoff_at\n"
            "          type: timestamp\n"
            "          nullable: true\n"
            "        - name: passenger_count\n"
            "          type: bigint\n"
            "          nullable: true\n"
            "        - name: distance_miles\n"
            "          type: double\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: total_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: tip_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: trip_source\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [yellow, green, fhv, fhvhv]\n"
            "\n"
            "    - name: silver.taxi_zone\n"
            "      alias: tz_pu\n"
            "      row_count: ~265\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: location_id\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 维度表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: zone_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: borough\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [Manhattan, Brooklyn, Queens, Bronx, Staten Island, EWR, Unknown]\n"
            "\n"
            "    - name: silver.taxi_zone\n"
            "      alias: tz_do\n"
            "      row_count: ~265\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: location_id\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 维度表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: zone_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: borough\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  joins:\n"
            "    - left_table: ft\n"
            "      right_table: tz_pu\n"
            "      left_key: pickup_location_id\n"
            "      right_key: location_id\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "    - left_table: ft\n"
            "      right_table: tz_do\n"
            "      left_key: dropoff_location_id\n"
            "      right_key: location_id\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: trip_id\n"
            "      type: varchar\n"
            "    - name: pickup_at\n"
            "      type: timestamp\n"
            "    - name: dropoff_at\n"
            "      type: timestamp\n"
            "    - name: passenger_count\n"
            "      type: bigint\n"
            "    - name: distance_miles\n"
            "      type: double\n"
            "    - name: fare_amount\n"
            "      type: decimal(12,2)\n"
            "    - name: total_amount\n"
            "      type: decimal(12,2)\n"
            "    - name: tip_amount\n"
            "      type: decimal(12,2)\n"
            "    - name: trip_source\n"
            "      type: varchar\n"
            "    - name: pickup_zone_name\n"
            "      type: varchar\n"
            "    - name: pickup_borough\n"
            "      type: varchar\n"
            "    - name: dropoff_zone_name\n"
            "      type: varchar\n"
            "    - name: dropoff_borough\n"
            "      type: varchar\n"
            "---\n"
            "\n"
            "# 行程明细宽表\n"
            "\n"
            "## 业务目标\n"
            "关联行程事实表和出租区域维表（两次 Join——上客+下客），展开区域名称和\n"
            "行政区等维度属性，产出行程明细宽表供下游分析使用。\n"
            "\n"
            "## 关联推理提示\n"
            "- ft.pickup_location_id → tz_pu.location_id（事实表上客区域编码 → 维表区域编码）\n"
            "- ft.dropoff_location_id → tz_do.location_id（事实表下客区域编码 → 维表区域编码）\n"
            "- 区域维表仅 265 行，两次 Join 均可全量内存匹配\n"
            "- 务必添加 pickup_at 时间过滤，避免 8032 万行全表扫描\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_window_topn",
        "name": "行政区 Top10 出租区域",
        "description": "窗口函数排名——ROW_NUMBER 按行政区分组，按行程量降序取 Top10 热门区域",
        "category": "window",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.borough_top10_zones\n"
            "  target_grain: [borough, location_id]\n"
            '  summary: "各行政区 Top10 热门出租区域——按行程量降序排名"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips\n"
            "      alias: ft\n"
            "      row_count: ~8032万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: pickup_location_id\n"
            "          type: integer\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "        - name: total_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "\n"
            "    - name: silver.taxi_zone\n"
            "      alias: tz\n"
            "      row_count: ~265\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: location_id\n"
            "          type: integer\n"
            "          nullable: false\n"
            "          unique: true  # 维度表键列，确保 LEFT JOIN 安全\n"
            "      business_columns:\n"
            "        - name: borough\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "          enum: [Manhattan, Brooklyn, Queens, Bronx, Staten Island, EWR, Unknown]\n"
            "        - name: zone_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: trip_count\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: trip_id\n"
            "      alias: trip_count\n"
            "    - metric_name: total_fare\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: total_amount\n"
            "      alias: total_fare\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: borough\n"
            "      column_ref: borough\n"
            "    - dimension_name: location_id\n"
            "      column_ref: location_id\n"
            "\n"
            "  joins:\n"
            "    - left_table: ft\n"
            "      right_table: tz\n"
            "      left_key: pickup_location_id\n"
            "      right_key: location_id\n"
            "      join_type: INNER  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: borough\n"
            "      type: varchar\n"
            "    - name: location_id\n"
            "      type: integer\n"
            "    - name: zone_name\n"
            "      type: varchar\n"
            "    - name: trip_count\n"
            "      type: bigint\n"
            "    - name: total_fare\n"
            "      type: decimal(12,2)\n"
            "    - name: rank_in_borough\n"
            "      type: int\n"
            "---\n"
            "\n"
            "# 各行政区 Top10 热门出租区域\n"
            "\n"
            "## 业务目标\n"
            "关联行程事实表和出租区域维表，按 borough 分组统计各区域的行程量和收入，\n"
            "使用 ROW_NUMBER 窗口函数按行程量降序排名，取各行政区 Top 10 热门区域。\n"
            "\n"
            "## 窗口函数说明\n"
            "ROW_NUMBER() OVER (PARTITION BY borough ORDER BY trip_count DESC) AS rank_in_borough\n"
            "外层 WHERE rank_in_borough <= 10 取 TopN。\n"
            "\n"
            "## 关联推理提示\n"
            "- ft.pickup_location_id → tz.location_id（事实表上客区域编码 → 维表区域编码）\n"
            "- 区域维表仅 265 行，INNER JOIN 过滤无上客位置信息的记录\n"
            "- 务必添加 pickup_at 时间过滤（如 2026 Q1），8032 万行全表扫描不可接受\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_empty",
        "name": "自定义空模板",
        "description": "空白模板——从零开始编写 DeveloperSpec，适合自定义需求",
        "category": "empty",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.目标表名\n"
            "  target_grain: [维度列1, 维度列2]\n"
            '  summary: "一句话描述业务目标"\n'
            "\n"
            "  time_range:\n"
            '    start: "2026-01-01"  # 数据起始日期\n'
            '    end: "2026-03-31"    # 数据截止日期（大事实表必须设定，否则触发 Q-VAL-TIME 阻塞）\n'
            "\n"
            "  source_tables:\n"
            "    - name: gold.fact_trips      # 可用：gold.fact_trips（8032万）/ gold.fact_crashes（166万）/ gold.fact_parking_violations（958万）\n"
            "      alias: ft                  # 别名（2-4个字母）\n"
            "      row_count: ~8032万         # 实际行数：fact_trips=8032万, fact_crashes=166万, parking=958万\n"
            "      role: fact                 # fact（事实表）| dim（维度表）\n"
            "      time_field: pickup_at      # 大事实表务必填写 time_field，配合 time_range 使用\n"
            "      key_columns:\n"
            "        - name: trip_id\n"
            "          type: varchar\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: pickup_at\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: distance_miles\n"
            "          type: double\n"
            "          nullable: true\n"
            "        - name: fare_amount\n"
            "          type: decimal(12,2)\n"
            "          nullable: true\n"
            "\n"
            "  metrics:                       # 指标声明（可选）\n"
            "    # - metric_name: trip_count\n"
            "    #   aggregation: COUNT       # SUM | COUNT | COUNT_DISTINCT | AVG | MAX | MIN\n"
            "    #   input_column: trip_id\n"
            "    #   alias: trip_count\n"
            "\n"
            "  dimensions:                    # 维度声明（可选）\n"
            "    # - dimension_name: pickup_date_key\n"
            "    #   column_ref: pickup_date_key\n"
            "\n"
            "  joins:                         # Join 声明（可选，多表时填写）\n"
            "    # 可用维度表：silver.taxi_zone（265行/location_id）, gold.dim_date（1.1万行/date_key）,\n"
            "    #            gold.dim_vehicle（11.9万行/vehicle_key）, gold.dim_base（1117行/base_key）\n"
            "    # 注意：维度表的 key_columns 需加 unique: true，否则 LEFT JOIN 安全门禁会阻塞\n"
            "    # - left_table: ft\n"
            "    #   right_table: tz\n"
            "    #   left_key: pickup_location_id\n"
            "    #   right_key: location_id\n"
            "    #   join_type: LEFT          # INNER | LEFT | RIGHT | FULL\n"
            "\n"
            "  output_columns:                # 输出列定义\n"
            "    # - name: trip_date\n"
            "    #   type: date\n"
            "---\n"
            "\n"
            "# 标题\n"
            "\n"
            "## 业务目标\n"
            "在此描述业务需求和分析目标。\n"
            "\n"
            "## 数据说明\n"
            "数据源：D:\\\\ProgramData\\\\Datawarehouse\\\\纽约市城市交通\\\\nyc_transport.duckdb\n"
            "可用表：bronze（原始层 16 表）/ silver（明细层 9 表）/ gold（聚合层 15 表）。\n"
            "时间范围：2009-2026，主数据集中在 2026 Q1。\n"
            "```\n"
        ),
    },
]
