"""Pipeline 预设 DeveloperSpec 模板。

从 Pipeline.TEMPLATES 类属性外置而来，减少核心文件视觉噪音。
提供 6 个 DeveloperSpec 模板供前端 SPA 使用：

- aggregation: 汇总表——单表聚合，按维度分组统计指标
- label: 标签表——CASE WHEN 分类打标
- multi_step: 多步骤加工——多表 Join + 聚合
- join: 两表 Join——事实表关联维度表展开宽表
- window: 窗口 TopN——ROW_NUMBER 分组排序取 TopN
- empty: 自定义空模板——从零开始编写
"""

TEMPLATES: list[dict] = [
    {
        "template_id": "tpl_aggregation",
        "name": "汇总表",
        "description": "单表聚合——按维度分组统计指标，如日活、销售额汇总",
        "category": "aggregation",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.metrics_daily\n"
            "  target_grain: [stat_date]\n"
            '  summary: "按日期汇总核心指标"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.user_events\n"
            "      alias: ue\n"
            "      row_count: ~1000万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: event_time\n"
            "      key_columns:\n"
            "        - name: id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: event_time\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "        - name: user_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "        - name: event_type\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: pv\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: id\n"
            "      alias: pv\n"
            "    - metric_name: uv\n"
            "      aggregation: COUNT_DISTINCT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: user_id\n"
            "      alias: uv\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: stat_date\n"
            "      column_ref: stat_date\n"
            "\n"
            "  output_columns:\n"
            "    - name: stat_date\n"
            "      type: date\n"
            "    - name: pv\n"
            "      type: bigint\n"
            "    - name: uv\n"
            "      type: bigint\n"
            "---\n"
            "\n"
            "# 汇总表模板\n"
            "\n"
            "## 业务目标\n"
            "按日期统计 PV 和 UV，产出日报表。\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_label_table",
        "name": "标签表",
        "description": "CASE WHEN 分类打标——按条件对数据进行分类标签加工",
        "category": "label",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: label_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.user_labels\n"
            "  target_grain: [user_id]\n"
            '  summary: "用户价值分层标签加工"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.user_orders\n"
            "      alias: uo\n"
            "      row_count: ~500万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: order_time\n"
            "      key_columns:\n"
            "        - name: user_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: order_amount\n"
            "          type: decimal(18,2)\n"
            "          nullable: true\n"
            "        - name: order_time\n"
            "          type: timestamp\n"
            "          nullable: false\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: total_amount\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: order_amount\n"
            "      alias: total_amount\n"
            "    - metric_name: order_cnt\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: user_id\n"
            "      alias: order_cnt\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: user_id\n"
            "      column_ref: user_id\n"
            "\n"
            "  output_columns:\n"
            "    - name: user_id\n"
            "      type: bigint\n"
            "    - name: total_amount\n"
            "      type: decimal(18,2)\n"
            "    - name: order_cnt\n"
            "      type: bigint\n"
            "    - name: value_level\n"
            "      type: varchar\n"
            "---\n"
            "\n"
            "# 标签表模板\n"
            "\n"
            "## 业务目标\n"
            "按用户汇总消费金额和订单数，输出价值分层标签。\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_multi_step",
        "name": "多步骤加工",
        "description": "多表 Join + 聚合——两表关联后分组统计，产出宽表",
        "category": "multi_step",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.order_analysis\n"
            "  target_grain: [order_date, category]\n"
            '  summary: "订单品类分析——订单表关联商品维度表"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.orders\n"
            "      alias: o\n"
            "      row_count: ~2000万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: order_date\n"
            "      key_columns:\n"
            "        - name: order_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: order_date\n"
            "          type: date\n"
            "          nullable: false\n"
            "        - name: order_amount\n"
            "          type: decimal(18,2)\n"
            "          nullable: true\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "    - name: dim.product\n"
            "      alias: p\n"
            "      row_count: ~10万\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: category\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: product_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: order_cnt\n"
            "      aggregation: COUNT  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: order_id\n"
            "      alias: order_cnt\n"
            "    - metric_name: total_amount\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: order_amount\n"
            "      alias: total_amount\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: order_date\n"
            "      column_ref: order_date\n"
            "    - dimension_name: category\n"
            "      column_ref: category\n"
            "\n"
            "  joins:\n"
            "    - left_table: o\n"
            "      right_table: p\n"
            "      left_key: product_id\n"
            "      right_key: product_id\n"
            "      join_type: INNER  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: order_date\n"
            "      type: date\n"
            "    - name: category\n"
            "      type: varchar\n"
            "    - name: order_cnt\n"
            "      type: bigint\n"
            "    - name: total_amount\n"
            "      type: decimal(18,2)\n"
            "---\n"
            "\n"
            "# 订单品类分析\n"
            "\n"
            "## 业务目标\n"
            "关联订单事实表和商品维度表，按日期和品类统计订单量和金额。\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_two_table_join",
        "name": "两表 Join",
        "description": "两表关联——事实表关联维度表，展开宽表字段，不做聚合",
        "category": "join",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: detail_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.order_detail_wide\n"
            "  target_grain: [order_id]\n"
            '  summary: "订单明细宽表——关联商品维度，展开品类和名称"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.orders\n"
            "      alias: o\n"
            "      row_count: ~2000万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: order_date\n"
            "      key_columns:\n"
            "        - name: order_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: order_date\n"
            "          type: date\n"
            "          nullable: false\n"
            "        - name: order_amount\n"
            "          type: decimal(18,2)\n"
            "          nullable: true\n"
            "        - name: user_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "    - name: dim.product\n"
            "      alias: p\n"
            "      row_count: ~10万\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: product_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: category\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: brand\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  joins:\n"
            "    - left_table: o\n"
            "      right_table: p\n"
            "      left_key: product_id\n"
            "      right_key: product_id\n"
            "      join_type: LEFT  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: order_id\n"
            "      type: bigint\n"
            "    - name: order_date\n"
            "      type: date\n"
            "    - name: order_amount\n"
            "      type: decimal(18,2)\n"
            "    - name: user_id\n"
            "      type: bigint\n"
            "    - name: product_name\n"
            "      type: varchar\n"
            "    - name: category\n"
            "      type: varchar\n"
            "    - name: brand\n"
            "      type: varchar\n"
            "---\n"
            "\n"
            "# 订单明细宽表\n"
            "\n"
            "## 业务目标\n"
            "关联订单事实表和商品维度表，展开商品名称、品类、品牌等维度属性，\n"
            "产出订单明细宽表供下游分析使用。\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_window_topn",
        "name": "窗口 TopN",
        "description": "窗口函数排名——ROW_NUMBER/RANK 分组排序取 TopN，如各品类销售额 Top10 商品",
        "category": "window",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.category_top10_product\n"
            "  target_grain: [category, product_id]\n"
            '  summary: "各品类销售额 Top10 商品排名"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.order_items\n"
            "      alias: oi\n"
            "      row_count: ~5000万\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: order_date\n"
            "      key_columns:\n"
            "        - name: item_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: order_date\n"
            "          type: date\n"
            "          nullable: false\n"
            "        - name: sale_amount\n"
            "          type: decimal(18,2)\n"
            "          nullable: true\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "    - name: dim.product\n"
            "      alias: p\n"
            "      row_count: ~10万\n"
            "      role: dim  # fact（事实表）| dim（维度表）\n"
            "      key_columns:\n"
            "        - name: product_id\n"
            "          type: bigint\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: category\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "        - name: product_name\n"
            "          type: varchar\n"
            "          nullable: true\n"
            "\n"
            "  metrics:\n"
            "    - metric_name: total_sales\n"
            "      aggregation: SUM  # COUNT（计数）| SUM（求和）| AVG（平均）| MIN（最小）| MAX（最大）| COUNT_DISTINCT（去重计数）\n"
            "      input_column: sale_amount\n"
            "      alias: total_sales\n"
            "\n"
            "  dimensions:\n"
            "    - dimension_name: category\n"
            "      column_ref: category\n"
            "    - dimension_name: product_id\n"
            "      column_ref: product_id\n"
            "\n"
            "  joins:\n"
            "    - left_table: oi\n"
            "      right_table: p\n"
            "      left_key: product_id\n"
            "      right_key: product_id\n"
            "      join_type: INNER  # INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:\n"
            "    - name: category\n"
            "      type: varchar\n"
            "    - name: product_id\n"
            "      type: bigint\n"
            "    - name: product_name\n"
            "      type: varchar\n"
            "    - name: total_sales\n"
            "      type: decimal(18,2)\n"
            "    - name: rank_in_category\n"
            "      type: int\n"
            "---\n"
            "\n"
            "# 各品类销售额 Top10 商品\n"
            "\n"
            "## 业务目标\n"
            "按品类分组，计算每个商品的销售额汇总，使用 ROW_NUMBER 窗口函数\n"
            "按销售额降序排名，取各品类 Top 10 商品。\n"
            "\n"
            "## 窗口函数说明\n"
            "使用 ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_sales DESC) 排名，\n"
            "外层 WHERE rank_in_category <= 10 取 TopN。\n"
            "```\n"
        ),
    },
    {
        "template_id": "tpl_empty",
        "name": "自定义空模板",
        "description": "空白模板——从零开始编写 DeveloperSpec，适合自定义需求",
        "category": "empty",
        "markdown_template": (
            "```markdown\n"
            "---\n"
            "spec:\n"
            "  type: aggregate_table  # aggregate_table（汇总表）| detail_table（明细表）| label_table（标签表）\n"
            "  target_table: ads.目标表名\n"
            "  target_grain: [维度列1, 维度列2]\n"
            '  summary: "一句话描述业务目标"\n'
            "\n"
            "  source_tables:\n"
            "    - name: dwd.源表名\n"
            "      alias: 别名（两个字母）\n"
            "      row_count: ~估算行数\n"
            "      role: fact  # fact（事实表）| dim（维度表）\n"
            "      time_field: 时间字段名      # 如有\n"
            "      key_columns:\n"
            "        - name: 主键列名\n"
            "          type: 类型              # bigint | varchar | ...\n"
            "          nullable: false\n"
            "      business_columns:\n"
            "        - name: 业务列名\n"
            "          type: 类型\n"
            "          nullable: true\n"
            "\n"
            "  metrics:                       # 指标声明（可选）\n"
            "    # - metric_name: 指标名\n"
            "    #   aggregation: SUM（求和）| COUNT（计数）| COUNT_DISTINCT（去重计数）| AVG（平均）| MAX（最大）| MIN（最小）\n"
            "    #   input_column: 输入列名\n"
            "    #   alias: 输出别名\n"
            "\n"
            "  dimensions:                    # 维度声明（可选）\n"
            "    # - dimension_name: 维度名\n"
            "    #   column_ref: 列引用\n"
            "\n"
            "  joins:                         # Join 声明（可选，多表时填写）\n"
            "    # - left_table: 左表别名\n"
            "    #   right_table: 右表别名\n"
            "    #   left_key: 左键列名\n"
            "    #   right_key: 右键列名\n"
            "    #   join_type: INNER（内连接）| LEFT（左连接）| RIGHT（右连接）| FULL（全连接）\n"
            "\n"
            "  output_columns:                # 输出列定义\n"
            "    # - name: 列名\n"
            "    #   type: 类型\n"
            "---\n"
            "\n"
            "# 标题\n"
            "\n"
            "## 业务目标\n"
            "在此描述业务需求和分析目标。\n"
            "\n"
            "## 数据说明\n"
            "在此补充数据源、字段含义、业务口径等说明。\n"
            "```\n"
        ),
    },
]
