"""DeveloperSpec 解析与 SourceManifest 构建。

Phase 1A 提供确定性解析、模型校验和事实源追踪能力。
"""

from .field_normalizer import FieldNormalizer, NormalizationConfig
from .models import (
    AggregationType,
    CaseWhenBranch,
    CaseWhenRule,
    ColumnDecl,
    ComputeStep,
    ConflictType,
    DerivedDimensionDecl,
    DimensionDecl,
    FieldSource,
    FilterDecl,
    ForeignKeyRef,
    HumanResolution,
    InputTableDecl,
    JoinDecl,
    JoinTypeEnum,
    ManifestAnomaly,
    ManifestColumn,
    ManifestTable,
    MetricDecl,
    OpenQuestion,
    OutputSpecDecl,
    ParsedDeveloperSpec,
    ParseWarning,
    RequirementPlannerOutput,
    RequirementProposal,
    SafeCsvPathLiteral,
    SafePhysicalTableName,
    SortDecl,
    SortDirection,
    SourceConflict,
    SourceManifest,
    StrictModel,
    TimeRangeDecl,
    UncertaintyEntry,
    WarningSeverity,
    _render_sql_string_literal,
)
from .parser import DeveloperSpecParser, ParseError, ParseErrorCode
from .source_manifest import SchemaRegistry, SnapshotProfile, SourceManifestBuilder

__all__ = [
    # 模型
    "StrictModel",
    "SafeCsvPathLiteral",
    "SafePhysicalTableName",
    "_render_sql_string_literal",
    "ParsedDeveloperSpec",
    "OpenQuestion",
    "ParseWarning",
    "SourceConflict",
    "HumanResolution",
    "InputTableDecl",
    "ColumnDecl",
    "MetricDecl",
    "DimensionDecl",
    "DerivedDimensionDecl",
    "CaseWhenBranch",
    "CaseWhenRule",
    "UncertaintyEntry",
    "RequirementPlannerOutput",
    "RequirementProposal",
    "JoinDecl",
    "TimeRangeDecl",
    "OutputSpecDecl",
    "SortDecl",
    "FilterDecl",
    "SourceManifest",
    "ManifestTable",
    "ManifestColumn",
    "FieldSource",
    "ManifestAnomaly",
    "ForeignKeyRef",
    "ComputeStep",
    # 枚举
    "AggregationType",
    "ConflictType",
    "JoinTypeEnum",
    "SortDirection",
    "WarningSeverity",
    # Parser
    "DeveloperSpecParser",
    "ParseError",
    "ParseErrorCode",
    # 归一化
    "FieldNormalizer",
    "NormalizationConfig",
    # SourceManifest
    "SourceManifestBuilder",
    "SchemaRegistry",
    "SnapshotProfile",
]
